% Plot errthang

tests = {"V_1_6_Cycles_10_TxHarsonics_with_skull.mat",...
	"V_1_6_Cycles_10_TxHarsonics_without_skull.mat",...
	"V_1_6_Cycles_10_TxISO_with_skull.mat", ...
	"V_1_6_Cycles_10_TxISO_without_skull.mat",...
	"V_1_6_Cycles_10_TxV301_with_skull.mat",...
	"V_1_6_Cycles_10_TxV301_without_skull.mat",...
	"V_7_Cycles_10_TxHarsonics_with_skull.mat",...
	"V_7_Cycles_10_TxHarsonics_without_skull.mat",...
	"V_7_Cycles_10_TxISO_with_skull.mat",...
	"V_7_Cycles_10_TxISO_without_skull.mat",...
	"V_7_Cycles_10_TxV301_with_skull.mat",...
	"V_7_Cycles_10_TxV301_without_skull.mat"
    };

count = 0;
tx ={"Harsonics", "ISO", "V301"};
V = {"1.6","7"};

for i = 1:2:4
    ind = mod(count,3)+1;
    if i <6
        plot_with_and_without_skull(tests{i},tests{i+1},1,tx{ind},V{1}, 3);
    else
        plot_with_and_without_skull(tests{i},tests{i+1},1,tx{ind},V{2});
    end
    count=count+1;
end
    